[package]
name = "sawzall"
version = "0.1.0"
edition = "2021"
authors = ["David Cornu <me@davidcornu.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
ego-tree = "0.10.0"
magnus = { version = "0.7.1" }
scraper = { version = "0.23.1", features = ["atomic"] }
